// <auto-generated />
using DoctorSampleApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorSampleApp.Migrations
{
    [DbContext(typeof(ManojkumarDRContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoctorSampleApp.Models.DoctorManagement", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DoctorDept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorFees")
                        .HasColumnType("int");

                    b.Property<string>("DoctorImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorQualification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.ToTable("DoctorTable");

                    b.HasData(
                        new
                        {
                            DoctorId = 111,
                            DoctorDept = "Surgery",
                            DoctorFees = 85000,
                            DoctorImage = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fimages.picxy.com%2Fcache%2F2020%2F7%2F11%2Ff10937541521489a327848bdd5e4d3ea.jpg&imgrefurl=https%3A%2F%2Fwww.picxy.com%2Fphoto%2F911013&tbnid=z5-jNdTZ2jVjRM&vet=12ahUKEwjXsOnFvcP6AhU6omoFHc-QDwMQMygmegUIARC3Ag..i&docid=lV6XLSPp0t7yRM&w=1068&h=1600&q=doctor%20images&ved=2ahUKEwjXsOnFvcP6AhU6omoFHc-QDwMQMygmegUIARC3Ag",
                            DoctorName = "Krishna",
                            DoctorQualification = "MBBS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
